### ISSUE TITLE
Delete index doesn't delete

### ISSUE THREAD

**Issue by movostudios** [mmanos/laravel-search#10]
Hey,

Firstly, thanks for this package - Awesome.

I have created a few indexes and in an attempt to build the management side of things, I have found that I can't delete an individual index:
<code>Search::index('users')->deleteIndex();</code>

If I then search for a result, it seems the index still exists. If I then:
<code>curl -XDELETE 'http://localhost:9200/users/'</code>
And repeat the search, the index has been deleted.

In this case I am using ElasticSearch.

I'll take a look to see if I can figure out what is going wrong here. In the meantime, if you can point me in the right direction, that would be awesome.

Cheers.

**Comment by dmyers** [comment]
Which version of Laravel & ElasticSearch client are you using?

**Comment by movostudios** [comment]
Sorry dude. I forgot all about this. I'm no longer using the package. Thanks for getting back.
