### ISSUE TITLE
Search->select only returns id and score. Cannot return other fields

### ISSUE THREAD

**Issue by paulfry** [mmanos/laravel-search#20]
Hi, the search returns only id and score. I cannot retrieve other fields.

Has anyone else had this issue?

Great package!!

**Comment by abrab** [comment]
+1 for this issue.
+1 for "Great package!!"

**Comment by fronterweb** [comment]
+1

**Comment by mmanos** [comment]
Hi guys, have you looked at the [store-extra-parameters-with-a-document](https://github.com/mmanos/laravel-search#store-extra-parameters-with-a-document) section of the readme? Will that solve your problem?

Not sure if that's what you are referring to...

**Comment by abrab** [comment]
@mmanos As for me, yes it is exactly what I needed. Just didn't understand the doc well. 
Thanks again for this great package.
