### ISSUE TITLE
Laravel 5.1 error

### ISSUE THREAD

**Issue by Rtransat** [mmanos/laravel-search#36]
Hi,

I have some issue with Laravel 5.1.

When I call the facade Search::search() for example, I have an error:

```Call to undefined method Mmanos\Search\Search::methodName```

It's me or your package is not compatible with Laravel 5.1 ?

With IoC I have no error but the result is an empty array.

Thx

**Comment by RyanThompson** [comment]
@Rtransat Im using this on 5.1 (LTS) right now and it's solid. @mmanos

**Comment by dmyers** [comment]
Not sure if reproducible @Rtransat.
