### ISSUE TITLE
Elasticsearch not working

### ISSUE THREAD

**Issue by hetunandu** [mmanos/laravel-search#39]
Error thrown when indexing:

Argument 1 passed to Elasticsearch\Client::__construct() must be an instance of Elasticsearch\Transport, array given

I have installed elasticsearch/elasticsearch (v2.1.3)

Please look into this matter

**Comment by Denisbeder** [comment]
I got the same error

**Comment by dmyers** [comment]
Can you try using an the `1.0` version of the ElasticSearch SDK? It's probably caused by the `2.0` version changes.

The package was developed with this Composer requirement in require-dev. Hopefully we can get it upgraded in the near future @mmanos.

```
 "elasticsearch/elasticsearch": "1.0.*@dev",
```

**Comment by kevinzheng** [comment]
Has this issue been fixed with elasticsearch/elasticsearch 2.0 ?

**Comment by francoism90** [comment]
I'm still getting this error, need to downgrade to ``1.0``.
