### ISSUE TITLE
Elasticsearch 2.3.3 supported?

### ISSUE THREAD

**Issue by zwl1619** [mmanos/laravel-search#47]
Elasticsearch 2.3.3 supported?

**Comment by thaoha** [comment]
As I see, this vendor is not support ES 2.3+ yet (at least 2.3 as I check :D).  You can check it at this line: https://github.com/mmanos/laravel-search/blob/master/src/Mmanos/Search/Index/Elasticsearch.php#L134

ES 2.3: 
`
        "filter" : {
            "geo_distance" : {
                "distance" : "200km",
                "pin.location" : {
                    "lat" : 40,
                    "lon" : -70
                }
            }
        }
`

**Comment by dmyers** [comment]
Sorry guys yeah the version that the [package was built with](https://github.com/mmanos/laravel-search/blob/master/composer.json#L17) was ~1.0, but the goal is to upgrade it of course to the latest supported.
