### ISSUE TITLE
Laravel 5 Support

### ISSUE THREAD

**Issue by tmunzar** [mmanos/laravel-search#8]
Just wondering if this will get Laravel 5 support anytime soon.

**Comment by nextpulse** [comment]
+1

**Comment by dschniepp** [comment]
@mmanos do you want to open a Larval 5 branch? Because I would like to contribute the Laravel 5 ready package.

**Comment by mmanos** [comment]
Thanks @dschniepp, I appreciate the help!

I'm not sure what the best approach is, but I've created a 0.0 branch for the current repo state, but want to keep using master for the latest code. So feel free to create a request against master. I'll create a new 1.0 tag when we get your code merged in.

**Comment by rogeryu23** [comment]
any update on this?

**Comment by dschniepp** [comment]
@rogeryu23 Laravel 5 support is available in the master-brach.
